name:                smerdyakov
version:             0.1.0.0
synopsis:
description:         Please see README.md
homepage:            http://github.com/jkarni/smerdyakov#README.md
license:             BSD3
license-file:        LICENSE
author:              Julian K. Arni
maintainer:          jkarni@gmail.com
copyright:           (c) Julian K. Arni
github:              jkarni/hask-deps
tested-with:         GHC == 7.8.3, GHC == 7.10.2, GHC == 8.0.1

ghc-options: -Wall

dependencies:
  - base >= 4.7 && < 4.10
  - process == 1.2.*
  - exceptions == 0.8.*
  - free == 4.12.*
  - transformers == 0.4.*
  - mtl == 2.2.*
  - text

default-extensions:
  - AutoDeriveTypeable
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveFunctor
  - DeriveGeneric
  - DeriveFoldable
  - DeriveTraversable
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - KindSignatures
  - MultiParamTypeClasses
  - OverloadedStrings
  - RankNTypes
  - RoleAnnotations
  - ScopedTypeVariables
  - TypeFamilies
  - TypeOperators

library:
  source-dirs:      src
  other-modules:    []

tests:
  spec:
    main:            Spec.hs
    source-dirs:     test
    dependencies:
      - smerdyakov
      - hspec > 2 && < 3
      - QuickCheck >= 2.8 && < 2.9
  doctest:
    main:            Doctest.hs
    source-dirs:     test
    dependencies:
      - doctest >= 0.9 && < 0.12
      - Glob >= 0.7 && < 0.8
      - yaml == 0.8.*

